### ISSUE TITLE
No spaces inside the tags allowed

### ISSUE THREAD

**Issue by cherry247** [cherry247/password-generator#4]
Since password field doesn't have spaces, so while entering input, make sure that it does not have spaces. if it does, then either it should 

1.  given alert/ warning to users that spaces are not allowed and let user manually remove the spaces
2. either remove that tag automatically
3. either remove the space in the input

<img src="https://github.com/cherry247/password-generator/assets/48171767/8f52b19a-3bc7-42cf-b3b0-ab3db13f44b9" width="500" height="300" />

**Comment by urvashiramdasani** [comment]
Already resolved by the previous commit. https://github.com/cherry247/password-generator/commit/88f3f42418e72626cd8b91dcbcd575ac1b457cdb

**Comment by cherry247** [comment]
resolved this using replace() method
